/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tg.trident.centurycinema.ticket_seller.reservation_panels;

import Model.CenturyModel;
import Model.Movie;
import Model.Screening;
import Model.TicketSeller;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tg.trident.centurycinema.CenturyCinema;
import tg.trident.centurycinema.ticket_seller.TicketSellerPage;

/**
 *
 * @author dagim
 */
public class TicketSuccessPage extends javax.swing.JPanel {
    
    private int screeningId;
    private String selectedSeats;
    public static String titlePrint;
    public static String releaseDatePrint;
    public static String durationPrint;
    public static double pricePrint;
    public static int room_numPrint;
    public static String periodPrint;
    public static String seatPrint;
    public static String user_namePrint;
    

    /**
     * Creates new form TicketSuccessPage
     */
    public TicketSuccessPage() {
        initComponents();
    }

    public void setData(int screeningId, ArrayList<String> selectedSeats){
        
        System.out.print("3");
        this.screeningId = screeningId;
        this.selectedSeats = "";
        
        //make string for selected seats
        for (String item : selectedSeats) {
             this.selectedSeats  += item + ", ";
        }
        if(this.selectedSeats .length() > 1)
            this.selectedSeats  = this.selectedSeats .substring(0, this.selectedSeats .length() - 2);
     
        
        Screening screening = CenturyModel.getScreeningById(screeningId);
        Movie movie = CenturyModel.getMovieById(screening.getMovie_id());
        TicketSeller ts = CenturyModel.getTicketSellerById(CenturyCinema.id);
        
        this.movie.setText("Movie: " + movie.getTitle() + "(" + movie.getRelease_date() + ") "+ movie.getDuration() + " minutes ");
        Double totalPrise = screening.getPrice() * selectedSeats.size();
        this.prise.setText("Prise: " + totalPrise);
        this.room.setText("Room: " + screening.getRoom_number());
        this.screening.setText("Screening: " + screening.getPeriod());
        this.seats.setText("Seats: " + this.selectedSeats);
        this.seller.setText("Ticket Seller: " + ts.getUser_name());
        
                System.out.print("4");
                     titlePrint = movie.getTitle();
     releaseDatePrint = movie.getRelease_date();
     durationPrint = movie.getDuration();
     pricePrint = screening.getPrice() * selectedSeats.size();
     room_numPrint = screening.getRoom_number();
     periodPrint = screening.getPeriod();
     seatPrint = this.selectedSeats;
     user_namePrint = ts.getUser_name();
        
    }
    public void clearData(){
         this.movie.setText("Movie: ");
        this.prise.setText("Prise: ");
        this.room.setText("Room: ");
        this.screening.setText("Screening: ");
        this.seats.setText("Seats: " );
        this.seller.setText("Ticket Seller: ");
        screeningId = -1;
        selectedSeats= "";
    }
    
    public void setPrintableData(int screeningId, ArrayList<String> selectedSeats){
        this.screeningId = screeningId;
        this.selectedSeats = "";
        
        //make string for selected seats
        for (String item : selectedSeats) {
             this.selectedSeats  += item + ", ";
        }
        if(this.selectedSeats .length() > 1)
            this.selectedSeats  = this.selectedSeats .substring(0, this.selectedSeats .length() - 2);
        
        Screening screening = CenturyModel.getScreeningById(screeningId);
        Movie movie = CenturyModel.getMovieById(screening.getMovie_id());
        TicketSeller ts = CenturyModel.getTicketSellerById(CenturyCinema.id);
        
     titlePrint = movie.getTitle();
     releaseDatePrint = movie.getRelease_date();
     durationPrint = movie.getDuration();
     pricePrint = screening.getPrice() * selectedSeats.size();
     room_numPrint = screening.getRoom_number();
     periodPrint = screening.getPeriod();
     seatPrint = this.selectedSeats;
     user_namePrint = ts.getUser_name();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        movie = new javax.swing.JLabel();
        prise = new javax.swing.JLabel();
        seller = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        screening = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        Print = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticket Confirmation");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(new java.awt.Color(37, 37, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ticket successfully booked");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        movie.setForeground(new java.awt.Color(255, 255, 255));
        movie.setText("Movie: ");

        prise.setForeground(new java.awt.Color(255, 255, 255));
        prise.setText("Prise:");

        seller.setForeground(new java.awt.Color(255, 255, 255));
        seller.setText("Ticket Seller:");

        seats.setForeground(new java.awt.Color(255, 255, 255));
        seats.setText("Seats: ");

        screening.setForeground(new java.awt.Color(255, 255, 255));
        screening.setText("Screening: ");

        room.setForeground(new java.awt.Color(255, 255, 255));
        room.setText("Room: ");

        Print.setBackground(new java.awt.Color(207, 145, 18));
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText("Print Ticket");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(146, 146, 146)
                        .addComponent(Print)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movie, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prise, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(screening, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Print))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screening, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prise, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        PrintToPdf p = new PrintToPdf();
        try {
            p.print(titlePrint, releaseDatePrint, durationPrint, pricePrint, room_numPrint, periodPrint, seatPrint, user_namePrint);
            JOptionPane.showMessageDialog(this, "Ticket Successfully Generedated. Please check your PDF Folder");
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(TicketSuccessPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel movie;
    private javax.swing.JLabel prise;
    private javax.swing.JLabel room;
    private javax.swing.JLabel screening;
    private javax.swing.JLabel seats;
    private javax.swing.JLabel seller;
    // End of variables declaration//GEN-END:variables
}
