/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tg.trident.centurycinema.ticket_seller;

/**
 *
 * @author dagim
 */
public class SelectScreening extends javax.swing.JPanel {

    /**
     * Creates new form AddReservation
     */
    public SelectScreening() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        filterDateButton = new tg.trident.centurycinema.buttons.GoldenButton();
        date = new javax.swing.JTextField();
        filterPeriodButton = new tg.trident.centurycinema.buttons.GoldenButton();
        period = new javax.swing.JComboBox<>();
        selectSeats = new tg.trident.centurycinema.buttons.GoldenButton();

        setBackground(new java.awt.Color(37, 37, 37));

        jComboBox1.setBackground(new java.awt.Color(58, 58, 58));
        jComboBox1.setForeground(new java.awt.Color(120, 120, 120));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO screenings for selected date and/or period." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        filterDateButton.setText("Filter by Date");
        filterDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDateButtonActionPerformed(evt);
            }
        });

        date.setBackground(new java.awt.Color(58, 58, 58));
        date.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        date.setForeground(new java.awt.Color(120, 120, 120));
        date.setText("Date (DD/MM/YY)");
        date.setPreferredSize(new java.awt.Dimension(315, 38));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        filterPeriodButton.setText("Filter by Period");
        filterPeriodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterPeriodButtonActionPerformed(evt);
            }
        });

        period.setBackground(new java.awt.Color(58, 58, 58));
        period.setForeground(new java.awt.Color(120, 120, 120));
        period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Period 1 ( 4:30 - 7:00 L.T)", "Period 2 ( 7:30 - 10:00 L.T)", "Period 3 ( 10:30 - 1:00 L.T)", "Period 4 ( 1:30 - 4:00 L.T)" }));
        period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodActionPerformed(evt);
            }
        });

        selectSeats.setText("Select Seats");
        selectSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(filterDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterPeriodButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(selectSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(period)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterPeriodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)))
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(selectSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void filterDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterDateButtonActionPerformed

    private void filterPeriodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterPeriodButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterPeriodButtonActionPerformed

    private void periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodActionPerformed

    private void selectSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSeatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private tg.trident.centurycinema.buttons.GoldenButton filterDateButton;
    private tg.trident.centurycinema.buttons.GoldenButton filterPeriodButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> period;
    private tg.trident.centurycinema.buttons.GoldenButton selectSeats;
    // End of variables declaration//GEN-END:variables
}
