/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tg.trident.centurycinema.admin;

import java.awt.Component;

/**
 *
 * @author dagim
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public AdminPage() {
        initComponents();
         changePanel(dashboard1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        addMovie2 = new tg.trident.centurycinema.admin.AddMovie();
        addRooms1 = new tg.trident.centurycinema.admin.AddRooms();
        dashboard1 = new tg.trident.centurycinema.admin.Dashboard();
        seeRooms1 = new tg.trident.centurycinema.admin.SeeRooms();
        settingPassword1 = new tg.trident.centurycinema.admin.SettingPassword();
        settingProfile1 = new tg.trident.centurycinema.admin.SettingProfile();
        ticketSellersUsers1 = new tg.trident.centurycinema.admin.TicketSellersUsers();
        userAnalytics1 = new tg.trident.centurycinema.admin.UserAnalytics();
        seeMovies1 = new tg.trident.centurycinema.admin.SeeMovies();
        addUser1 = new tg.trident.centurycinema.admin.AddUser();
        deleteMovie1 = new tg.trident.centurycinema.admin.DeleteMovie();
        jMenuBar1 = new javax.swing.JMenuBar();
        dashboard = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        mainPage = new javax.swing.JMenuItem();
        ticketSellers = new javax.swing.JMenu();
        users = new javax.swing.JMenuItem();
        addUser = new javax.swing.JMenuItem();
        userAnalytics = new javax.swing.JMenuItem();
        rooms = new javax.swing.JMenu();
        addRoom = new javax.swing.JMenuItem();
        seeRooms = new javax.swing.JMenuItem();
        deletemovie = new javax.swing.JMenu();
        addMovie = new javax.swing.JMenuItem();
        deleteMovie = new javax.swing.JMenuItem();
        seeMovie = new javax.swing.JMenuItem();
        settings = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        password = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(37, 37, 37));
        container.setLayout(new java.awt.CardLayout());
        container.add(addMovie2, "card2");
        container.add(addRooms1, "card3");
        container.add(dashboard1, "card4");
        container.add(seeRooms1, "card5");
        container.add(settingPassword1, "card6");
        container.add(settingProfile1, "card7");
        container.add(ticketSellersUsers1, "card8");
        container.add(userAnalytics1, "card9");
        container.add(seeMovies1, "card10");
        container.add(addUser1, "card11");

        deleteMovie1.setForeground(new java.awt.Color(255, 255, 255));
        container.add(deleteMovie1, "card12");

        jMenuBar1.setBackground(new java.awt.Color(64, 61, 61));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(800, 58));

        dashboard.setBackground(new java.awt.Color(37, 37, 37));
        dashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.setToolTipText("");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard.setMargin(new java.awt.Insets(0, 200, 0, 0));
        dashboard.setPreferredSize(new java.awt.Dimension(100, 23));
        dashboard.setRequestFocusEnabled(false);
        dashboard.setRolloverEnabled(false);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logout.setBackground(new java.awt.Color(64, 61, 61));
        logout.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setMargin(new java.awt.Insets(0, 0, 0, 0));
        logout.setOpaque(true);
        logout.setPreferredSize(new java.awt.Dimension(150, 40));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        dashboard.add(logout);

        mainPage.setBackground(new java.awt.Color(64, 61, 61));
        mainPage.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        mainPage.setForeground(new java.awt.Color(255, 255, 255));
        mainPage.setText("MainPage");
        mainPage.setBorder(null);
        mainPage.setBorderPainted(false);
        mainPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainPage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mainPage.setOpaque(true);
        mainPage.setPreferredSize(new java.awt.Dimension(150, 40));
        mainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageActionPerformed(evt);
            }
        });
        dashboard.add(mainPage);

        jMenuBar1.add(dashboard);
        dashboard.getAccessibleContext().setAccessibleName("dashboard");

        ticketSellers.setBackground(new java.awt.Color(37, 37, 37));
        ticketSellers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ticketSellers.setForeground(new java.awt.Color(255, 255, 255));
        ticketSellers.setText("Ticket Sellers");
        ticketSellers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketSellers.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ticketSellers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ticketSellers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ticketSellers.setMargin(new java.awt.Insets(3, 10, 3, 6));
        ticketSellers.setPreferredSize(new java.awt.Dimension(100, 23));
        ticketSellers.setRolloverEnabled(false);

        users.setBackground(new java.awt.Color(64, 61, 61));
        users.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        users.setMargin(new java.awt.Insets(0, 10, 0, 6));
        users.setOpaque(true);
        users.setPreferredSize(new java.awt.Dimension(150, 40));
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        ticketSellers.add(users);

        addUser.setBackground(new java.awt.Color(64, 61, 61));
        addUser.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        addUser.setForeground(new java.awt.Color(255, 255, 255));
        addUser.setText("AddUser'");
        addUser.setBorder(null);
        addUser.setBorderPainted(false);
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addUser.setMargin(new java.awt.Insets(0, 10, 0, 6));
        addUser.setOpaque(true);
        addUser.setPreferredSize(new java.awt.Dimension(150, 40));
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        ticketSellers.add(addUser);

        userAnalytics.setBackground(new java.awt.Color(64, 61, 61));
        userAnalytics.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        userAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        userAnalytics.setText("User Analytics");
        userAnalytics.setBorder(null);
        userAnalytics.setBorderPainted(false);
        userAnalytics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAnalytics.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userAnalytics.setMargin(new java.awt.Insets(0, 6, 0, 6));
        userAnalytics.setOpaque(true);
        userAnalytics.setPreferredSize(new java.awt.Dimension(150, 40));
        userAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnalyticsActionPerformed(evt);
            }
        });
        ticketSellers.add(userAnalytics);

        jMenuBar1.add(ticketSellers);

        rooms.setBackground(new java.awt.Color(37, 37, 37));
        rooms.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rooms.setForeground(new java.awt.Color(255, 255, 255));
        rooms.setText("Rooms");
        rooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rooms.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rooms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rooms.setMargin(new java.awt.Insets(3, 10, 3, 6));
        rooms.setPreferredSize(new java.awt.Dimension(75, 23));
        rooms.setRolloverEnabled(false);

        addRoom.setBackground(new java.awt.Color(64, 61, 61));
        addRoom.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        addRoom.setForeground(new java.awt.Color(255, 255, 255));
        addRoom.setText("Add Room");
        addRoom.setBorder(null);
        addRoom.setBorderPainted(false);
        addRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRoom.setMargin(new java.awt.Insets(0, 6, 0, 6));
        addRoom.setOpaque(true);
        addRoom.setPreferredSize(new java.awt.Dimension(150, 40));
        addRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomActionPerformed(evt);
            }
        });
        rooms.add(addRoom);

        seeRooms.setBackground(new java.awt.Color(64, 61, 61));
        seeRooms.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        seeRooms.setForeground(new java.awt.Color(255, 255, 255));
        seeRooms.setText("SeeRooms");
        seeRooms.setBorder(null);
        seeRooms.setBorderPainted(false);
        seeRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeRooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seeRooms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seeRooms.setMargin(new java.awt.Insets(0, 6, 0, 6));
        seeRooms.setOpaque(true);
        seeRooms.setPreferredSize(new java.awt.Dimension(150, 40));
        seeRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeRoomsActionPerformed(evt);
            }
        });
        rooms.add(seeRooms);

        jMenuBar1.add(rooms);

        deletemovie.setBackground(new java.awt.Color(37, 37, 37));
        deletemovie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deletemovie.setForeground(new java.awt.Color(255, 255, 255));
        deletemovie.setText("Movies");
        deletemovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletemovie.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deletemovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletemovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deletemovie.setMargin(new java.awt.Insets(3, 10, 3, 6));
        deletemovie.setPreferredSize(new java.awt.Dimension(75, 23));
        deletemovie.setRolloverEnabled(false);

        addMovie.setBackground(new java.awt.Color(64, 61, 61));
        addMovie.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        addMovie.setForeground(new java.awt.Color(255, 255, 255));
        addMovie.setText("Add Movie");
        addMovie.setBorder(null);
        addMovie.setBorderPainted(false);
        addMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMovie.setMargin(new java.awt.Insets(0, 6, 0, 6));
        addMovie.setOpaque(true);
        addMovie.setPreferredSize(new java.awt.Dimension(150, 40));
        addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieActionPerformed(evt);
            }
        });
        deletemovie.add(addMovie);

        deleteMovie.setBackground(new java.awt.Color(64, 61, 61));
        deleteMovie.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        deleteMovie.setForeground(new java.awt.Color(255, 255, 255));
        deleteMovie.setText("Delete Movie");
        deleteMovie.setBorder(null);
        deleteMovie.setBorderPainted(false);
        deleteMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteMovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteMovie.setMargin(new java.awt.Insets(0, 6, 0, 6));
        deleteMovie.setOpaque(true);
        deleteMovie.setPreferredSize(new java.awt.Dimension(150, 40));
        deleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieActionPerformed(evt);
            }
        });
        deletemovie.add(deleteMovie);

        seeMovie.setBackground(new java.awt.Color(64, 61, 61));
        seeMovie.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        seeMovie.setForeground(new java.awt.Color(255, 255, 255));
        seeMovie.setText("SeeMovies");
        seeMovie.setBorder(null);
        seeMovie.setBorderPainted(false);
        seeMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeMovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seeMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seeMovie.setMargin(new java.awt.Insets(0, 6, 0, 6));
        seeMovie.setOpaque(true);
        seeMovie.setPreferredSize(new java.awt.Dimension(150, 40));
        seeMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMovieActionPerformed(evt);
            }
        });
        deletemovie.add(seeMovie);

        jMenuBar1.add(deletemovie);

        settings.setBackground(new java.awt.Color(37, 37, 37));
        settings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        settings.setForeground(new java.awt.Color(255, 255, 255));
        settings.setText("Settings");
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settings.setMargin(new java.awt.Insets(3, 10, 3, 6));
        settings.setPreferredSize(new java.awt.Dimension(75, 23));
        settings.setRolloverEnabled(false);

        profile.setBackground(new java.awt.Color(64, 61, 61));
        profile.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profile.setMargin(new java.awt.Insets(0, 6, 0, 6));
        profile.setOpaque(true);
        profile.setPreferredSize(new java.awt.Dimension(150, 40));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        settings.add(profile);

        password.setBackground(new java.awt.Color(64, 61, 61));
        password.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setBorder(null);
        password.setBorderPainted(false);
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        password.setMargin(new java.awt.Insets(0, 6, 0, 6));
        password.setOpaque(true);
        password.setPreferredSize(new java.awt.Dimension(150, 40));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        settings.add(password);

        jMenuBar1.add(settings);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        changePanel(dashboard1);
    }//GEN-LAST:event_logoutActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
        changePanel(ticketSellersUsers1);
    }//GEN-LAST:event_usersActionPerformed

    private void userAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnalyticsActionPerformed
        // TODO add your handling code here:
        changePanel(userAnalytics1);
    }//GEN-LAST:event_userAnalyticsActionPerformed

    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomActionPerformed
        // TODO add your handling code here:
        changePanel(addRooms1);
    }//GEN-LAST:event_addRoomActionPerformed

    private void addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieActionPerformed
        // TODO add your handling code here:
        changePanel(addMovie2);
    }//GEN-LAST:event_addMovieActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        changePanel(settingProfile1);
    }//GEN-LAST:event_profileActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        changePanel(settingPassword1);
    }//GEN-LAST:event_passwordActionPerformed

    private void mainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageActionPerformed
        // TODO add your handling code here:
        changePanel(dashboard1);
    }//GEN-LAST:event_mainPageActionPerformed

    private void seeRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeRoomsActionPerformed
        // TODO add your handling code here:
        changePanel(seeRooms1);
    }//GEN-LAST:event_seeRoomsActionPerformed

    private void seeMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMovieActionPerformed
        // TODO add your handling code here:
        changePanel(seeMovies1);
    }//GEN-LAST:event_seeMovieActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
         changePanel(addUser1);
    }//GEN-LAST:event_addUserActionPerformed

    private void deleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieActionPerformed
        // TODO add your handling code here:
         changePanel(deleteMovie1);
    }//GEN-LAST:event_deleteMovieActionPerformed
    public void changePanel(Component c){
           container.removeAll();
           container.repaint();
           container.revalidate();
           container.add(c);
           container.repaint();
           container.revalidate();
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMovie;
    private tg.trident.centurycinema.admin.AddMovie addMovie2;
    private javax.swing.JMenuItem addRoom;
    private tg.trident.centurycinema.admin.AddRooms addRooms1;
    private javax.swing.JMenuItem addUser;
    private tg.trident.centurycinema.admin.AddUser addUser1;
    private javax.swing.JPanel container;
    private javax.swing.JMenu dashboard;
    private tg.trident.centurycinema.admin.Dashboard dashboard1;
    private javax.swing.JMenuItem deleteMovie;
    private tg.trident.centurycinema.admin.DeleteMovie deleteMovie1;
    private javax.swing.JMenu deletemovie;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem mainPage;
    private javax.swing.JMenuItem password;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenu rooms;
    private javax.swing.JMenuItem seeMovie;
    private tg.trident.centurycinema.admin.SeeMovies seeMovies1;
    private javax.swing.JMenuItem seeRooms;
    private tg.trident.centurycinema.admin.SeeRooms seeRooms1;
    private tg.trident.centurycinema.admin.SettingPassword settingPassword1;
    private tg.trident.centurycinema.admin.SettingProfile settingProfile1;
    private javax.swing.JMenu settings;
    private javax.swing.JMenu ticketSellers;
    private tg.trident.centurycinema.admin.TicketSellersUsers ticketSellersUsers1;
    private javax.swing.JMenuItem userAnalytics;
    private tg.trident.centurycinema.admin.UserAnalytics userAnalytics1;
    private javax.swing.JMenuItem users;
    // End of variables declaration//GEN-END:variables
}
