/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tg.trident.centurycinema.admin;

import Model.CenturyModel;
import Model.Movie;
import java.awt.List;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author abelcosmic
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        ArrayList<Movie> movies = CenturyModel.getAllMovies();
        ArrayList<String> todayImageUrls = new ArrayList<>();
        ArrayList<String> title = new ArrayList<>();
        ArrayList<String> subtitle = new ArrayList<>();
        movies.forEach(movie -> {
            todayImageUrls.add(movie.getPoster());
        });
        movies.forEach(movie-> {
            title.add(movie.getTitle());
        });
         movies.forEach(movie-> {
          subtitle.add(movie.getGenre());
        });
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setText(generateHTMLCode(todayImageUrls,todayImageUrls,title,subtitle));      

    }

    private static String generateHTMLCode(ArrayList<String> todayImageUrls, ArrayList<String> tomorrowImageUrls,ArrayList<String> title ,ArrayList<String> subtitle) {
        StringBuilder htmlBuilder = new StringBuilder();
        htmlBuilder.append("<!DOCTYPE html>\n")
                .append("<html lang=\"en\">\n")
                .append("<head>\n")
                .append("    <meta charset=\"UTF-8\">\n")
                .append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
                .append("    <title>Document</title>\n")
                .append("</head>\n")
                .append("<body>\n")
                .append("    <table>\n")
                .append("        <tr>\n")
                .append("            <td colspan=\"2\"><h1>TODAY'S WATCH LIST</h1></td>\n")
                .append("        </tr>\n")
                .append("        <tr>\n");

        for (String imageUrl : todayImageUrls) {
            htmlBuilder
                    .append("            <td>\n")
                    .append("                <img src=\"").append(imageUrl).append("\">\n")
                    .append("                <h1>").append(title).append("</h1>\n")
                    .append("                <h3>").append(subtitle).append("</h3>\n")
                    .append("            </td>\n");
            System.out.println(imageUrl);
        }
        htmlBuilder.append("        </tr>\n");

        htmlBuilder.append("        <tr>\n")
                .append("            <td colspan=\"2\"><h1>TOMORROW'S WATCH LIST</h1></td>\n")
                .append("        </tr>\n")
                .append("        <tr>\n");

        for (String imageUrl : tomorrowImageUrls) {
            htmlBuilder
                    .append("            <td>\n")
                    .append("                <img src=\"").append(imageUrl).append("\">\n")
                    .append("                <h1>").append(title).append("</h1>\n")
                   .append("                <h3>").append(subtitle).append("</h3>\n")
                    .append("            </td>\n");
        }
        htmlBuilder.append("        </tr>\n");

        htmlBuilder.append("    </table>\n")
                .append("</body>\n")
                .append("</html>");

        return htmlBuilder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 37, 37));

        jEditorPane1.setBackground(new java.awt.Color(37, 37, 37));
        jEditorPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jEditorPane1);

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
